-- liquibase formatted sql
-- changeset msuzko:init_db

CREATE TABLE instruments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker varchar(10) NOT NULL UNIQUE,
    price NUMERIC NOT NULL DEFAULT 0
);

--rollback DROP TABLE IF EXISTS instruments;